### ISSUE TITLE
Error 6074 when recompiling dsdt.dsl

### ISSUE THREAD

**Issue by kingCazales** [zachsmith/x1yg3-suspend-to-ram#3] opened 2019-05-08 21:22 UTC
BIOS (1.30)
Operating System: KDE neon 5.15
KDE Plasma Version: 5.15.5
KDE Frameworks Version: 5.57.0
Qt Version: 5.12.0
Kernel Version: 4.18.0-18-generic
OS Type: 64-bit
Processors: 8 × Intel® Core™ i5-8250U CPU @ 1.60GHz
Memory: 7.6 GiB of RAM

[dsdt.dat.zip](https://github.com/zachsmith/x1yg3-suspend-to-ram/files/3159339/dsdt.dat.zip)

This is the final part of the terminal output:

 `dsdt.dsl  28136:         STDV,   8, 
Error    6074 -            ^ Name already exists in scope (STDV)

    Original name creation/declaration below: 
    dsdt.dsl    257:     External (STDV, IntObj)

ASL Input:     dsdt.dsl - 35395 lines, 1108027 bytes, 15560 keywords
Hex Dump:      dsdt.hex - 1386933 bytes

Compilation complete. 63 Errors, 347 Warnings, 125 Remarks, 6371 Optimizations, 51 Constants Folded
`

**Comment by zachsmith** [comment] 2019-05-09 05:12
Thanks for the report and all the information. I downloaded the `dsdt.dat` file you attached, decompiled it, and patched it successfully so I was not able to reproduce.

What version of `iasl` do you have? I'm using `20181213`

```shell
$ iasl -v

Intel ACPI Component Architecture
ASL+ Optimizing Compiler/Disassembler version 20181213
Copyright (c) 2000 - 2018 Intel Corporation
```

**Comment by kingCazales** [comment] 2019-05-09 19:45
I have version 20180105
`Intel ACPI Component Architecture
ASL+ Optimizing Compiler/Disassembler version 20180105
Copyright (c) 2000 - 2018 Intel Corporation`

I can't seem to find another version of it via terminal.
I tried to recompile on an Ubuntu 18.04 device with the same  ACPI version, and it was the same issue.

**Comment by zachsmith** [comment] 2019-05-10 04:24
You could try building an updated version of the `acpicatools` by [downloading the source](https://acpica.org/downloads) and following the simple build instructions. I just downloaded and built version `20190509` and was able to decompile, patch, and recompile your `dsdt.dat` file using the `iasl` binary I built.

**Comment by kingCazales** [comment] 2019-05-10 07:26
Thank you I was able to decompile, patch, and recompile by downloading version 20190509 with no errors.
I ran into another issue though, I could not create the directory 
`/etc/dracut.conf/acpi.conf`
`mkdir: cannot create directory ‘/etc/dracut.conf’: File exists`

So I tried to place my `acpi.conf` file in my `/etc/dracut.conf.d/` directory, and tried to rebuild the initramfs image and got this output:

dracut: Executing: /usr/bin/dracut --force initramfs-4.18.0-18-generic.img
dracut: dracut module 'bootchart' will not be installed, because command '/sbin/bootchartd' could not be found!
dracut: dracut module 'modsign' will not be installed, because command 'keyctl' could not be found!
dracut: dracut module 'plymouth' will not be installed, because command 'plymouth-set-default-theme' could not be found!
dracut: dracut module 'btrfs' will not be installed, because command 'btrfs' could not be found!
dracut: dracut module 'biosdevname' will not be installed, because command 'biosdevname' could not be found!
dracut: dracut module 'masterkey' will not be installed, because command 'keyctl' could not be found!
dracut: dracut module 'modsign' will not be installed, because command 'keyctl' could not be found!
dracut: dracut module 'btrfs' will not be installed, because command 'btrfs' could not be found!
dracut: dracut module 'masterkey' will not be installed, because command 'keyctl' could not be found!
dracut: *** Including module: bash ***
dracut: *** Including module: dash ***
dracut: *** Including module: systemd ***
dracut: *** Including module: systemd-initrd ***
dracut: *** Including module: console-setup ***
dracut: *** Including module: aufs ***
dracut: *** Including module: kernel-modules ***
dracut: *** Including module: overlay-root ***
dracut: *** Including module: resume ***
dracut: *** Including module: rootfs-block ***
dracut: *** Including module: terminfo ***
dracut: *** Including module: udev-rules ***
dracut: Skipping udev rule: 40-redhat.rules
dracut: Skipping udev rule: 91-permissions.rules
dracut: Skipping udev rule: 80-drivers-modprobe.rules
dracut: *** Including module: dracut-systemd ***
dracut: *** Including module: usrmount ***
dracut: *** Including module: base ***
dracut: *** Including module: fs-lib ***
dracut: *** Including module: shutdown ***
dracut: *** Including modules done ***
dracut-install: Failed to find module 'crc32c'
dracut: FAILED:  /usr/lib/dracut/dracut-install -D /var/tmp/dracut.TQuYoh/initramfs --kerneldir /lib/modules/4.18.0-18-generic/ -m crc32c
dracut: *** Installing kernel module dependencies ***
dracut: *** Installing kernel module dependencies done ***
dracut: *** Resolving executable dependencies ***
dracut: *** Resolving executable dependencies done***
dracut: *** Stripping files ***
dracut: *** Stripping files done ***
dracut: *** Generating early-microcode cpio image ***
dracut: *** Constructing GenuineIntel.bin ****
dracut: *** Store current command line parameters ***
dracut: Stored kernel commandline:
dracut:  resume=UUID=8f167eff-101f-43d4-abd4-28282f1997bd
dracut:  root=UUID=464a0e80-57f7-433f-81c0-0549e6ca107f rootfstype=ext4 rootflags=rw,relatime,errors=remount-ro
dracut: *** Creating image file '/boot/initramfs-4.18.0-18-generic.img' ***
dracut: *** Creating initramfs image file '/boot/initramfs-4.18.0-18-generic.img' done ***

Sorry for all the Issues!

**Comment by zachsmith** [comment] 2019-05-10 15:01
You discovered a bug in the instructions. I made the change to the instructions here to fix the [dracut.conf.d path fix](https://github.com/zachsmith/x1yg3-suspend-to-ram/pull/5/files). 

But it sounds like you had already put your updated `acpi.conf` file correctly in `/etc/dracut.d.conf/` so that doesn't explain your errors. I don't think the `acpi.conf` file is the issue here but you could confirm that by removing it from `/etc/dracut.d.conf` and trying to build the initramfs again. 

This current problem seems likely to be a distro specific issue so you may want to check the documentation on generating `initramfs` for Ubuntu/Neon. Looks like maybe Ubuntu uses `update-initramfs` script but that probably isn't the whole story. _See the [update-initramfs man page](http://manpages.ubuntu.com/manpages/cosmic/man8/live-update-initramfs.8.html)_. 

I'm sorry, but I probably can't help diagnose issues on other distributions so if you figure it out, can you open a pull request with instructions for Ubuntu/Neon?

**Comment by kingCazales** [comment] 2019-05-11 06:47
I was finally able to use `s2idle [deep]` without updating __initramfs_ __image_,  after reading this post: https://askubuntu.com/questions/1027552/including-a-custom-acpi-dsdt-with-kubuntu-18-04-rc1

Although I'm not sure if I will have to change the custom.cfg file in the grub folder when my kernel updates.
Should I still open a pull request?

**Comment by zachsmith** [comment] 2019-05-12 15:07
Glad you got something working! 

I'm not sure that will work with each kernel update and I worry that if there is an error in the DSDT you may not even get a grub boot screen as I think think the `acpi` command is run by grub before the boot menu is displayed.

However, it looks like Ubuntu may supply a mechanism for custom `DSDT.aml` to be picked up with each `initramfs` update. According to [the mkinitramfs man page](http://manpages.ubuntu.com/manpages/disco/man8/mkinitramfs.8.html), you can [re]name the table you built as `DSDT.aml`, place it in `/etc/initramfs-tools/`, and then run:

```shell
mkinitramfs -o /boot/initramfs-$(uname -r)
```

My hope is that we can find a solution that will persist across kernel updates so that the instructions are equivalent for each distribution. Would you mind giving it a shot and report back if it works? If so, we can work on a PR then.

**Comment by kingCazales** [comment] 2019-05-16 05:09
I could not enable `s2idle [deep]` with `mkinitramfs`

I moved my DSDT.aml to /etc/initramfs-tools/ and ran
 `sudo mkinitramfs -o /boot/initramfs-$(uname -r)`
This was the output:
`I: The initramfs will attempt to resume from /dev/nvme0n1p6
I: (UUID=8f167eff-101f-43d4-abd4-28282f1997bd)
I: Set the RESUME variable to override this.
`

**Comment by zachsmith** [comment] 2019-05-31 22:36
I'm going to go ahead and close this. Sounds like you're up and running. Also, it appears that Lenovo added S3 support in BIOS 1.34 so if you're not running that check it out.

**Closed as completed by zachsmith** 2019-05-31 22:36 UTC
